### ISSUE TITLE
CDDL vs JAS (JAEN)

### ISSUE THREAD

**Issue by athiasjerome** [sacmwg/draft-ietf-sacm-coswid#1]
More of a pointer/open question for the experts than an issue while I'm trying to figure out how potentially avoid potential duplication of efforts in the representation of overlapping schemas
https://github.com/OpenC2-org/jaen

**Comment by henkbirkholz** [comment]
Regarding a quite a few fundamental design principles CDDL is explicitly designed not to be a schema language. If a CDDL-2-JAEN converter is developed it seems feasible to support interoperability of tools. As this issue seems not to have an impact on the process of finalizing CDDL, I am porpoising to table this issue for now until JAS reaches a state, at which point it becomes feasible to talk about interoperability.

Without objection from the CBOR WG, this issue will be closed one day before the next moratorium (2018-07-01 (Sunday)).

**Comment by henkbirkholz** [comment]
Closed with negligible delay ;)
